repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: black
        language: system
        types: [python]